### PR TITLE
SECURESIGN-190 | swap to go-tools builder image

### PR DESCRIPTION
**Pull request by Gregory-Pereira**
Tested by copying the dockerfile into the branch `midstream/midstream-v2.2.0` and works like a charm. Ready for review and QE.
/cc @osmman 
/cc @lance

### CODE REVIEW

**Comment by osmman** [comment]
Hi, I think it is better to keep usage of multistage build. It will keep final image more cleaner without unnecessary resources like source code and building tools.

**Comment by Gregory-Pereira** [comment]
More info, when I was building the image, I was getting first `go: inconsistent vendoring in /cosign:` error, which I have fixed by calling `go mod vendor`. After that I am encountering another issue: `package <package-name> imports <dependency-package-name>:  build constraints exclude all Go files in <dependency-package-path>` which lead me to this thread (https://github.com/golang/go/issues/24433). This explained to me that the issue I am getting is because I am trying to build cross platform and my CGO_ENABLED is set to 0, which I would like to keep if possible as a requirement for the future FIPS compliancy task. I am wondering if you have encoutered this issue @RobotSail when cross-compiling binaries as you are also on Darwin?

**Comment by RobotSail** [comment]
@Gregory-Pereira I've never seen that error before, sorry I can't be of much help here.

**Review by lance — COMMENTED** [review]
I agree with @osmman that we should retain the multi-stage build here. To do that, you would just need to replace `FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder AS build-env` with `FROM registry.access.redhat.com/ubi9/go-toolset@sha256:9a0f860e143f2f771bee92ab3b0161e10e2390370152e07e6bcf8105242cee13`. Do you get errors with that approach and no other changes?

**Comment by lance** [comment]
closing this as obsolete now that we are working on tp2

**Pull request closed without merging**
