### PR TITLE
chore: move overlays to root in sync script

### PR DESCRIPTION
**Pull request by lance**
For RHTAP the Dockerfile needs to be in one of a limited set of locations. The easiest to deal with is at root.

Moving Dockerfile to `./overlays` instead of `./overlays/cosign` so that we can just have a generic move of all files under overlays and any directory structure is copied, instead of picking files from specific directories and moving them.

### CODE REVIEW

**Review by sallyom — APPROVED** [review]
LGTM!

**Review by JasonPowr — APPROVED** [review]
/lgtm

**Review by mayaCostantini — APPROVED** [review]

**Pull request merged**
